-- Migration: extend jobs fields + add job_posts (multi-job publish page)

ALTER TABLE jobs ADD COLUMN requirements MEDIUMTEXT DEFAULT NULL;
ALTER TABLE jobs ADD COLUMN responsibilities MEDIUMTEXT DEFAULT NULL;
ALTER TABLE jobs ADD COLUMN salary_min INT DEFAULT NULL;
ALTER TABLE jobs ADD COLUMN salary_max INT DEFAULT NULL;
ALTER TABLE jobs ADD COLUMN salary_note VARCHAR(255) DEFAULT NULL;
ALTER TABLE jobs ADD COLUMN location VARCHAR(255) DEFAULT NULL;
ALTER TABLE jobs ADD COLUMN employment_type VARCHAR(64) DEFAULT NULL;
ALTER TABLE jobs ADD COLUMN experience_level VARCHAR(64) DEFAULT NULL;
ALTER TABLE jobs ADD COLUMN education VARCHAR(64) DEFAULT NULL;
ALTER TABLE jobs ADD COLUMN benefits MEDIUMTEXT DEFAULT NULL;
ALTER TABLE jobs ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'open';
ALTER TABLE jobs ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS job_posts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(64) NOT NULL,
  description MEDIUMTEXT DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'published',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_job_posts_slug (slug)
);

CREATE TABLE IF NOT EXISTS job_post_jobs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  post_id BIGINT NOT NULL,
  job_id BIGINT NOT NULL,
  ord INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_jpj_post FOREIGN KEY (post_id) REFERENCES job_posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_jpj_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
  UNIQUE KEY uq_post_ord (post_id, ord),
  UNIQUE KEY uq_post_job (post_id, job_id)
);

